### ISSUE TITLE
希望能给bing的逆向加一个切换cookie的功能

### ISSUE THREAD

**Issue by o3oGekkou** [RockChinQ/revLibs#102]
希望能给bing的逆向加一个切换cookie的功能，这样就可以在一个账户达到每日限制后，换到另一个号，谢谢

**Comment by RockChinQ** [comment]
bing这个cookie取出来的有效期大概是几天，有测试过吗？

**Comment by RockChinQ** [comment]
acheong08/EdgeGPT 现已处于不可用状态
