### ISSUE TITLE
 'pkg.openai.dprompt' has no attribute 'get_prompt'

### ISSUE THREAD

**Issue by Sincejunly** [RockChinQ/revLibs#103]
请您认真填写以下信息。

### 任务

- [√] 我已严格按照文档中的步骤操作
- [√] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：（例如：New Bing）
New Bing
### 期望情况

我希望的情况是：正常回复？

### 实际情况

实际情况是：
```
[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "G:\YiriMirai\QChatGPT\plugins\revLibs\main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "G:\YiriMirai\QChatGPT\plugins\revLibs\pkg\process\procmsg.py", line 58, in process_message
    raise e
  File "G:\YiriMirai\QChatGPT\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "G:\YiriMirai\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
    dprompt_ = dprompt.get_prompt(dprompt.get_current())
AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
```
更新了以下openai好像也没用，

**Comment by Sincejunly** [comment]
国内不能用new bing？

**Comment by RockChinQ** [comment]
这是一个兼容性问题，你下载了主程序最新的源码，其中更多情景预设模块已重构，但逆向库插件未适配新的情景预设模块，故造成此问题。请先使用主程序的Release页面中的最新版源码重新部署主程序

**Comment by CBEpt** [comment]
> 这是一个兼容性问题，你下载了主程序最新的源码，其中情景预设模块已重构，但由于主程序还没有发版本，逆向库插件未适配新的情景预设模块，故造成此问题。请先使用主程序的Release页面中的最新版源码重新部署主程序

使用自动部署， qcg-installer-0.1-windows-x64.exe，主程序默认采用最新的源码？。。请问应该用release版本替换哪一部分的最新源码？

**Comment by RockChinQ** [comment]
> > 这是一个兼容性问题，你下载了主程序最新的源码，其中情景预设模块已重构，但由于主程序还没有发版本，逆向库插件未适配新的情景预设模块，故造成此问题。请先使用主程序的Release页面中的最新版源码重新部署主程序
> 
> 使用自动部署， qcg-installer-0.1-windows-x64.exe，主程序默认采用最新的源码？。。请问应该用release版本替换哪一部分的最新源码？

将下载的源码替换自动部署生成的QChatGPT目录下的内容

**Comment by RockChinQ** [comment]
已修复
