### ISSUE TITLE
QQ指令和Git Pull都无法成功更新插件

### ISSUE THREAD

**Issue by DannyLI0319** [RockChinQ/revLibs#107]
请您认真填写以下信息。

### 任务

- [Yes] 我已严格按照文档中的步骤操作
- [Yes] 我已经搜索了相关的issue

### 预期/正在使用的逆向库
我要使用的逆向库是：（例如：New Bing）
New Bing

### 期望情况
我希望的情况是：
可以通过机器人指令更新插件

### 实际情况
实际情况是：
通过机器人指令更新插件，说成功了，但是实际上插件并未更新。然后手动用git pull更新，也失败。只能把整个rev文件夹删了，重新安装部署一次插件，才能成功更新。

用机器人!plugin update更新显示成功，但是看了下config-template等文件的修改时间，还是之前的，没有动。
![image](https://user-images.githubusercontent.com/120266145/228407990-359ad7c1-b842-4c41-8091-0beb3285ba7a.png)

尝试手动git pull更新结果显示请保存变更，然后自动取消更新
![3 X_)CB%)M58`HPQTH380LH](https://user-images.githubusercontent.com/120266145/228408148-17d7ad57-3763-4612-9bfa-5b343794dadb.png)

最后我按这个步骤完整重新做了次，才成功更新：
https://github.com/RockChinQ/revLibs/issues/66#issuecomment-1471384381

**Comment by RockChinQ** [comment]
`git pull`拉不下来的情况先执行以下命令:

```bash
git reset --hard
```

将分支置于最后一次提交处，再进行`git pull`

**Comment by DannyLI0319** [comment]
也不行：
![image](https://user-images.githubusercontent.com/120266145/228415825-8402d84c-1473-45f8-b898-ec0af1df955b.png)

**Comment by RockChinQ** [comment]
dulwich问题，将更换插件更新方式，请在此跟踪 https://github.com/RockChinQ/QChatGPT/issues/384，在此之前建议通过删除插件后重装的方式进行更新。
