### ISSUE TITLE
!plugin update和gitpull更新插件无反应

### ISSUE THREAD

**Issue by McPeter111** [RockChinQ/revLibs#111]
请您认真填写以下信息。

### 任务

- [ √] 我已严格按照文档中的步骤操作
- [ √] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

New Bing

### 期望情况

我希望的情况是：更新插件

### 实际情况

实际情况是：
![image](https://user-images.githubusercontent.com/121279581/229809732-26ca7011-1728-41b3-9cf3-be9acc951ec3.png)
![image](https://user-images.githubusercontent.com/121279581/229809826-54d18698-b57d-428e-a5e1-d6155ccd0752.png)
接下来就没有任何动静了，只能重装。

**Comment by RockChinQ** [comment]
目前基本只能重装，因为主程序更新使用的`dulwich`库对多提交的仓库的支持不太好

**Comment by RockChinQ** [comment]
dulwich问题，将更换插件更新方式，请在此跟踪 https://github.com/RockChinQ/QChatGPT/issues/384
