### ISSUE TITLE
希望使用switcher插件在rgpt-3.5和newbing之间切换，如何设置reverse_lib参数

### ISSUE THREAD

**Issue by lieyanqzu** [RockChinQ/revLibs#116]
请您认真填写以下信息。

### 任务

- [x] 我已严格按照文档中的步骤操作
- [x] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：chatGPT + New Bing

### 期望情况

我希望的情况是：使用switcher插件在rgpt-3.5和newbing之间切换

### 实际情况

实际情况是：reverse_lib参数只能选择其中一个逆向库

**Comment by RockChinQ** [comment]
随便写个就行，你比如写的是`acheong08/EdgeGPT`，那么启动时就会默认使用`New Bing`，但是你仍然可以在运行期间通过指令进行切换

**Comment by lieyanqzu** [comment]
> 随便写个就行，你比如写的是`acheong08/EdgeGPT`，那么启动时就会默认使用`New Bing`，但是你仍然可以在运行期间通过指令进行切换

试了一下，切换之后由于之前的会话没有清掉，ChatGPT切Bing会在当前会话里切不过去，Bing切ChatGPT会话id丢失错误
我尝试在switcher里切换时清空sessions就好了，建议看看怎么做一下处理
