### ISSUE TITLE
逆向库高版本的兼容性问题

### ISSUE THREAD

**Issue by qq255204159** [RockChinQ/revLibs#120]
请您认真填写以下信息。

### 预期/正在使用的逆向库 ，目前最新版本

我要使用的逆向库是：（例如：chat3.5逆向）

### 期望情况

我希望的情况是：chat3.5逆向正常运行

### 实际情况

实际情况是：chat3.5逆向正常运行，但终端刷屏报错信息

![2M90TFX9E3 %V6$YV}` @O](https://user-images.githubusercontent.com/108674296/232370437-06164c61-af77-46d7-b5fe-1c187463b665.png)

1. 这里判定基本原因是，因为我的主体config与新版本config-template.py模板文件变量同步时，发现提示信息变量整合至另一个tips.py文件，以至逆向库主体加载找不到报错处理信息变量。
![L{BI{Q@1HKLWO{NTYZTFUAD](https://user-images.githubusercontent.com/108674296/232370721-103fe610-1aa5-49d5-9d91-0abdc9e4895f.png)

**Comment by RockChinQ** [comment]
已修复
