### ISSUE TITLE
请问能不能搞个revlibs的多账户模式吖

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/revLibs#14]
RT，比如我有5个openai账户，每个问题或者每五分钟随机切换一个账户，那么我每小时可使用量就翻了五倍

**Comment by CBEpt** [comment]
为何感觉没有实现多账号? 。。。 在群内多人回复感觉还是很慢。。。比如说我有三个号，1，2，3，有七个用户，按提问先后顺序排列为abcdefg。

可不可以用户a提问，账号1提供回答。
然后很快啊！1秒钟之后用户b提问，就把请求并发到第二个号？然后C去第三个号。。

感觉目前多个用户提问，用的是一个号去回复？等半分钟甚至更长才能得到回复。。日志里也没有体现出用到了我添加的另外两个号。

还是说我的设置出现了问题？。。求大佬解答，感谢！

**Comment by CBEpt** [comment]
> 目前逆向多账号单个账号与会话绑定，仅在创建新会话时轮换账号，因为逆向库的历史记录由服务端管理，你说的这种并发方式会导致会话内的前文记不住

比如说 我夹在多个用户请求中间，这时候回复很慢，
我只能!next  切换到后一次会话，才能换一个号问问题来得到快速的回复吗

**Comment by RockChinQ** [comment]
> > 目前逆向多账号单个账号与会话绑定，仅在创建新会话时轮换账号，因为逆向库的历史记录由服务端管理，你说的这种并发方式会导致会话内的前文记不住
> 
> 比如说 我夹在多个用户请求中间，这时候回复很慢， 我只能!next 切换到后一次会话，才能换一个号问问题来得到快速的回复吗

只有reset时才会轮换

**Comment by CBEpt** [comment]
群组中的bot可不可以自动!reset呢？ 比如用户a和c的问题很可能毫不相干，而此时如果不reset，ai就会使劲联系上下文，花费很长的时间来回答问题，造成响应慢。

如果用户c提问之前，先输一个!reset，重置整个对话，获取答案就会快很多。。不知大佬我说的对吗？

如果没问题，那么可不可以来自不同用户的新对话都加一个!reset 自动重置 切换另一个账号获取更快的回复？（虽然这样并发的时候不能**联系上下文**了。。不过**联系上下文**本来也就和**并发**不太兼容）

**Comment by RockChinQ** [comment]
> 群组中的bot可不可以自动!reset呢？ 比如用户a和c的问题很可能毫不相干，而此时如果不reset，ai就会使劲联系上下文，花费很长的时间来回答问题，造成响应慢。
> 
> 如果用户c提问之前，先输一个!reset，重置整个对话，获取答案就会快很多。。不知大佬我说的对吗？
> 
> 如果没问题，那么可不可以来自不同用户的新对话都加一个!reset 自动重置 切换另一个账号获取更快的回复？（虽然这样并发的时候不能**联系上下文**了。。不过**联系上下文**本来也就和**并发**不太兼容）

程序如何检测某问题与前文无关？

**Comment by RockChinQ** [comment]
你这个是群组内区分用户分别会话的问题，目前此功能已标记为不会实现

**Comment by CBEpt** [comment]
> > 群组中的bot可不可以自动!reset呢？ 比如用户a和c的问题很可能毫不相干，而此时如果不reset，ai就会使劲联系上下文，花费很长的时间来回答问题，造成响应慢。
> > 如果用户c提问之前，先输一个!reset，重置整个对话，获取答案就会快很多。。不知大佬我说的对吗？
> > 如果没问题，那么可不可以来自不同用户的新对话都加一个!reset 自动重置 切换另一个账号获取更快的回复？（虽然这样并发的时候不能**联系上下文**了。。不过**联系上下文**本来也就和**并发**不太兼容）
> 
> 程序如何检测某问题与前文无关并自动重置？

如果人很多的话，其实都会是毫不相干？（）

**Comment by RockChinQ** [comment]
> > > 群组中的bot可不可以自动!reset呢？ 比如用户a和c的问题很可能毫不相干，而此时如果不reset，ai就会使劲联系上下文，花费很长的时间来回答问题，造成响应慢。
> > > 如果用户c提问之前，先输一个!reset，重置整个对话，获取答案就会快很多。。不知大佬我说的对吗？
> > > 如果没问题，那么可不可以来自不同用户的新对话都加一个!reset 自动重置 切换另一个账号获取更快的回复？（虽然这样并发的时候不能**联系上下文**了。。不过**联系上下文**本来也就和**并发**不太兼容）
> > 
> > 程序如何检测某问题与前文无关并自动重置？
> 
> 如果人很多的话，其实都会是与前文毫不相干？（）如果一直都是考虑上下文，多用户一直使用一个账号的一个会话（多账号此时也成了摆设，除非!reset.........），还需要排队，等待回复的体验很差。。。

如果需要继续讨论此问题，请开新issue
