### ISSUE TITLE
插件一直卡在安装依赖

### ISSUE THREAD

**Issue by StellarJourney823** [RockChinQ/revLibs#144]
请您认真填写以下信息。

### 任务

- [] 我已严格按照文档中的步骤操作
- [ ] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：ChatGPT网页版GPT-4模型

### 期望情况

我希望的情况是：正常使用

### 实际情况

实际情况是：一直卡在安装依赖

**Comment by RockChinQ** [comment]
那程序应该已经下载了插件了，你就关闭程序，自行安装依赖再启动程序

**Comment by StellarJourney823** [comment]
自行安装依赖怎么操作？

**Comment by StellarJourney823** [comment]
> 那程序应该已经下载了插件了，你就关闭程序，自行安装依赖再启动程序

您好，自行安装依赖怎么操作？

**Comment by RockChinQ** [comment]
取决于你用的是什么部署方式

**Comment by StellarJourney823** [comment]
> 取决于你用的是什么部署方式

我使用的是整合包，QQ登录框架是go-cqhttp

**Comment by StellarJourney823** [comment]
> 取决于你用的是什么部署方式

用的是社区群里面的一健部署包

**Comment by StellarJourney823** [comment]
> > 取决于你用的是什么部署方式
> 
> 用的是社区群里面的一健部署包

我是直接在我电脑上使用的

**Comment by StellarJourney823** [comment]
> 取决于你用的是什么部署方式

大佬，可以帮我解决吗？我请你喝奶茶

**Comment by RockChinQ** [comment]
或者你尝试挂个网络代理再安装插件也行

**Comment by StellarJourney823** [comment]
> 或者你尝试挂个网络代理再安装插件也行

挂网络代理没用，我接下来尝试手动部署看看

**Comment by StellarJourney823** [comment]
> 或者你尝试挂个网络代理再安装插件也行

[2023-05-16 15:10:59.596] V1.py (322) - [ERROR] : Insufficient login details provided!
[2023-05-16 15:10:59.598] main.py (120) - [ERROR] : [rev] Traceback (most recent call last):
  File "C:\Users\LianYiLi\QChatGPT\plugins\revLibs\main.py", line 113, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\QChatGPT\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 137, in get_session
    __sessions__[name] = RevSession(name)
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 46, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\QChatGPT\plugins\revLibs\pkg\process\impls\v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\QChatGPT\plugins\revLibs\pkg\process\impls\v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
                   ^^^^^^^^
  File "C:\Users\LianYiLi\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 177, in __init__
    self.__check_credentials()
  File "C:\Users\LianYiLi\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 198, in __check_credentials
    self.login()
  File "C:\Users\LianYiLi\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LianYiLi\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 324, in login
    raise error
revChatGPT.typings.AuthenticationError: Insufficient login details provided!
Please check if your key is correct, maybe it may not be valid
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT

**Comment by StellarJourney823** [comment]
> 或者你尝试挂个网络代理再安装插件也行

老哥，我账号密码都对了，为什么会出现这个报错？

**Comment by StellarJourney823** [comment]
> 或者你尝试挂个网络代理再安装插件也行

老哥，我解决了，我换了一种登录方式。老哥，我怎么赞助你？想转钱给你，请你喝奶茶

**Comment by RockChinQ** [comment]
现在不能账密登录，只能用access_token登录；赞助可以查看res/目录下的收款码

**Comment by StellarJourney823** [comment]
> 现在不能账密登录，只能用access_token登录；赞助可以查看res/目录下的收款码

老哥，我找不到res/目录

**Comment by RockChinQ** [comment]
主程序目录下 https://github.com/RockChinQ/QChatGPT/tree/master/res

**Comment by StellarJourney823** [comment]
> 主程序目录下 https://github.com/RockChinQ/QChatGPT/tree/master/res

搞定，老哥，怎么修改调用API的机器人前缀为GPT-3.5。设置里只有GPT

**Comment by StellarJourney823** [comment]
> > > 主程序目录下 https://github.com/RockChinQ/QChatGPT/tree/master/res
> > 
> > 
> > 搞定，老哥，怎么修改调用API的机器人前缀为GPT-3.5。设置里只有GPT
> 
> 主程序不支持设置前缀的内容，只能设置是否显示前缀

好的！谢谢

**Comment by StellarJourney823** [comment]
> > > 主程序目录下 https://github.com/RockChinQ/QChatGPT/tree/master/res
> > 
> > 
> > 搞定，老哥，怎么修改调用API的机器人前缀为GPT-3.5。设置里只有GPT
> 
> 主程序不支持设置前缀的内容，只能设置是否显示前缀

老哥，ChatGPT网页版更新了。ChatGPT有三个版本：1.最开始的GPT-4 ，2.联网的GPT-4，3.支持插件调用的GPT-4

老哥，能让插件直接调用联网的GPT-4吗？

**Comment by StellarJourney823** [comment]
> > > > > 主程序目录下 https://github.com/RockChinQ/QChatGPT/tree/master/res
> > > > 
> > > > 
> > > > 搞定，老哥，怎么修改调用API的机器人前缀为GPT-3.5。设置里只有GPT
> > > 
> > > 
> > > 主程序不支持设置前缀的内容，只能设置是否显示前缀
> > 
> > 
> > 老哥，ChatGPT网页版更新了。ChatGPT有三个版本：1.最开始的GPT-4 ，2.联网的GPT-4，3.支持插件调用的GPT-4
> > 老哥，能让插件直接调用联网的GPT-4吗？
> 
> 暂时不能，之后也不一定会支持，一是ChatGPT逆向库停止维护了，二是我没有plus账号

好吧，老哥，plus账号，我可以借给你

**Comment by RockChinQ** [comment]
> > > > > > 主程序目录下 https://github.com/RockChinQ/QChatGPT/tree/master/res
> > > > > 
> > > > > 
> > > > > 搞定，老哥，怎么修改调用API的机器人前缀为GPT-3.5。设置里只有GPT
> > > > 
> > > > 
> > > > 主程序不支持设置前缀的内容，只能设置是否显示前缀
> > > 
> > > 
> > > 老哥，ChatGPT网页版更新了。ChatGPT有三个版本：1.最开始的GPT-4 ，2.联网的GPT-4，3.支持插件调用的GPT-4
> > > 老哥，能让插件直接调用联网的GPT-4吗？
> > 
> > 暂时不能，之后也不一定会支持，一是ChatGPT逆向库停止维护了，二是我没有plus账号
> 
> 好吧，老哥，plus账号，我可以借给你

如果需要再找你吧，最近事情多比较忙

**Comment by StellarJourney823** [comment]
> > > > > > > 主程序目录下 https://github.com/RockChinQ/QChatGPT/tree/master/res
> > > > > > 
> > > > > > 
> > > > > > 搞定，老哥，怎么修改调用API的机器人前缀为GPT-3.5。设置里只有GPT
> > > > > 
> > > > > 
> > > > > 主程序不支持设置前缀的内容，只能设置是否显示前缀
> > > > 
> > > > 
> > > > 老哥，ChatGPT网页版更新了。ChatGPT有三个版本：1.最开始的GPT-4 ，2.联网的GPT-4，3.支持插件调用的GPT-4
> > > > 老哥，能让插件直接调用联网的GPT-4吗？
> > > 
> > > 
> > > 暂时不能，之后也不一定会支持，一是ChatGPT逆向库停止维护了，二是我没有plus账号
> > 
> > 
> > 好吧，老哥，plus账号，我可以借给你
> 
> 如果需要再找你吧，最近事情多比较忙

嗯嗯，好的
