### ISSUE TITLE
回复时报错

### ISSUE THREAD

**Issue by Heathlia** [RockChinQ/revLibs#147]
我要使用的逆向库是：ChatGPT网页版
报错如图
<img width="867" alt="image" src="https://github.com/RockChinQ/revLibs/assets/99574412/b62f91de-d650-46a8-b3ad-04eb9d283925">

**Comment by RockChinQ** [comment]
access token不可用，确保账户未被冻结，重新按照revcfg.py中的说明填写鉴权相关字段
