### ISSUE TITLE
[Feature]: 增加对 xtekky/gpt4free 的支持

### ISSUE THREAD

**Issue by o3oGekkou** [RockChinQ/revLibs#153]
### 这是一个？

新功能

### 详细描述

https://github.com/xtekky/gpt4free    希望可以集成这个项目，白嫖gpt4

**Comment by RockChinQ** [comment]
gpt4free项目为逆向工程项目，转移issue到此revLibs插件仓库

**Comment by RockChinQ** [comment]
g4f现已处于完全不可用状态

**Comment by RockChinQ** [comment]
现已支持，请更新revLibs插件并在按照此仓库文档进行配置
