### ISSUE TITLE
gpt网页版逆向库无法支持场景预设？

### ISSUE THREAD

**Issue by ling0403** [RockChinQ/revLibs#159]
逆向库：ChatGPT网页版
1.若默认场景预设不为default时，输入任何信息都会报错，且无法使用!reset指令切换场景预设
2.当使用[Switcher插件](https://github.com/RockChinQ/Switcher)切换接口到gpt官方3.5接口时，场景预设及!reset指令正常运行，此时切换场景预设到default后再次切换到gpt网页版逆向库接口后，聊天功能恢复，但是使用!reset指令失败，依旧无法切换场景预设

报错代码如下图:

![20230522002802](https://github.com/RockChinQ/revLibs/assets/110319440/ec66f3cc-c0e2-4b09-aafd-6d1809a254ee)

**Comment by RockChinQ** [comment]
两个问题：
1. 检查你是否按照配置文件中的说明正确使用access_token配置了ChatGPT账号信息
2. 主程序不是最新，请使用`!update`更新主程序，再使用`!plugin update revLibs`更新此插件

**Comment by RockChinQ** [comment]
第二段报错的原因就是主程序或插件未更新到最新版本

**Comment by RockChinQ** [comment]
已查明是bug 请等待修复

**Comment by ling0403** [comment]
很奇怪，没有更新任何东西，但是网页版逆向库貌似又能支持场景预设了（在设置好情景预设的前提下切换接口），只是会报一次错并卡死不回复任何信息，使用!reload后场景预设又能正常运行，报错如下：
![1](https://github.com/RockChinQ/revLibs/assets/110319440/eda24deb-5c49-4a52-814d-2f90443fb750)

2.但是此时使用!reset 时依然报错（与之前一致）:
![2](https://github.com/RockChinQ/revLibs/assets/110319440/8cc607be-7a9f-441d-93a8-ac672bee8bda)
