### ISSUE TITLE
使用hugchat时会报错加载模块失败

### ISSUE THREAD

**Issue by ZheiPP** [RockChinQ/revLibs#168]
请您认真填写以下信息。

### 任务

- [ ] 我已严格按照文档中的步骤操作
- [ ] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：hugchat（例如：New Bing）

### 期望情况

我希望的情况是：

### 实际情况

实际情况是：
![image](https://github.com/RockChinQ/revLibs/assets/132807883/45823976-f5b0-409f-a0c2-63e76f669515)

**Comment by Enceladus6** [comment]
我也遇到了一样的问题

**Comment by RockChinQ** [comment]
你这个hugchat的依赖没装好，自行安装一下python的依赖或者删除逆向库插件后重新安装此插件

**Comment by Enceladus6** [comment]
重装好几次了，依然是这样

**Comment by Enceladus6** [comment]
解决了，原本 用的清华源，使用官方源重装就好了

**Comment by RockChinQ** [comment]
对的，建议能用官方源就用官方源
