### ISSUE TITLE
如何修改rGPT3.5逆向的会话保留时间？

### ISSUE THREAD

**Issue by Enceladus6** [RockChinQ/revLibs#175]
如题，我在config.py 修改时间为86400，但依然提示
[2023-06-01 18:01:33.912] main.py (106) - [INFO] : [rev] 已将主程序消息处理超时时间设置为10分钟
其他也找不到修改时间的地方

**Comment by RockChinQ** [comment]
超时时间跟你这个过期时间不是一个东西，超时时间是单次响应判为失败前的等待时间

**Comment by Enceladus6** [comment]
有办法让逆向的3.5每天的会话都保持在一个conversation里面吗？

**Comment by RockChinQ** [comment]
不同的会话（群、人）开始或reset时会创建新conversation，目前没有自动删除的功能

**Comment by Enceladus6** [comment]
好的感谢，那我就不管他了
