### ISSUE TITLE
使用New Bing，向机器人发送信息后出错

### ISSUE THREAD

**Issue by Sprt98** [RockChinQ/revLibs#198]
请您认真填写以下信息。

### 任务

- [ ] 我已严格按照文档中的步骤操作
- [ ] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：New Bing

### 期望情况

我希望的情况是：向机器人发送信息，机器人能回复。

### 实际情况

实际情况是：
出现这个错误：

![nbcw](https://github.com/RockChinQ/revLibs/assets/100029295/afd89b9c-4322-4321-952c-ed7876f6a77c)

**Comment by RockChinQ** [comment]
不清楚，仔细检查是否按照文档填写new bing的cookies

**Comment by RockChinQ** [comment]
NewBing最近都没法用了，请关注 https://github.com/acheong08/EdgeGPT 的动态
