### ISSUE TITLE
请问私聊和群聊各有不同报错

### ISSUE THREAD

**Issue by nD9r2Dhr** [RockChinQ/revLibs#234]
### 任务

- ☑️ 我已严格按照文档中的步骤操作
- ☑️ 我已经搜索了相关的issue

### 正在使用的逆向库
revChatGPT 6.8.6

#### 情况一:
![](https://i0.imgs.ovh/2024/02/15/omx6d.png)
![](https://i0.imgs.ovh/2024/02/15/omsPl.png)
#### 情况二: (移除了 https://github.com/RockChinQ/revLibs/commit/46fe719680c652f0de897788d08059ef7066a21f)
把发送量统计的代码暂时移除了
这时第一个开启的群聊/私聊会话无报错，开启的第二个群聊/私聊会话报错如下:
![](https://i0.imgs.ovh/2024/02/15/ombG2.png)

请佬看一下，是不是 OPENAI 又更新了😭

**Comment by RockChinQ** [comment]
很不幸，现在revChatGPT 完全处于不可用状态（大约于大前天更新的新的反爬策略，我的号也被封了）
