### ISSUE TITLE
能否自动catch报错 ，并换号，至少也要不要打印到群里

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/revLibs#27]

**Comment by RockChinQ** [comment]
仅在报错一小时请求过多时才会切换账号

**Comment by r5rinimaa** [comment]
您好，经验表明，任何一个错误一但出现，一段时间内的发问仍然不会回答甚至报错，而reload必然能解决这个问题，能否报错就自动reload

**Comment by RockChinQ** [comment]
> 您好，经验表明，任何一个错误一但出现，一段时间内的发问仍然不会回答甚至报错，而reload必然能解决这个问题，能否报错就自动reload

应该先尝试修复问题，而不是忽略问题。请提供出现此问题时的控制台信息

**Comment by r5rinimaa** [comment]
好的，问题是千奇百怪的，等再遇到了我贴上来

**Comment by r5rinimaa** [comment]
如果我想修改代码catch报错，我该在哪个文件里面catch，才能不打印到群里呢

**Comment by RockChinQ** [comment]
> 如果我想修改代码catch报错，我该在哪个文件里面catch，才能不打印到群里呢

正在做，主程序目前支持此功能 RockChinQ/QChatGPT#121，即将在逆向库支持此功能

**Comment by RockChinQ** [comment]
已实现，请更新并根据 https://github.com/RockChinQ/QChatGPT/issues/121 设置
