### ISSUE TITLE
支持chatGPT和GPT3切换，建议增加自定义唤起命令以调用chatGPT回复

### ISSUE THREAD

**Issue by LINSTCL** [RockChinQ/revLibs#37]

**Comment by DerilJust** [comment]
现在有办法在运行时切换网页版chatGPT和API的GPT吗，想用GPT4

**Comment by RockChinQ** [comment]
> 现在有办法在运行时切换网页版chatGPT和API的GPT吗，想用GPT4

目前有插件开关功能，可以在运行期间使用`!plugin off revLibs`指令禁用逆向库插件

**Comment by RockChinQ** [comment]
安装[此插件](https://github.com/RockChinQ/Switcher)，即可在使用中切换文字模型。
