### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by zhenianchuyu** [RockChinQ/revLibs#40]
![image](https://user-images.githubusercontent.com/53022996/222305350-32b54426-3183-4ee6-8e5b-cb1cda116239.png)
revLibs插件安装成功，配置好文件，已经重载、重启过主程序，但后面发现又变回API回复了，于是想热重载主程序，就报上图的错误了

**Comment by RockChinQ** [comment]
#1
