### ISSUE TITLE
大佬用的何种vpn呀我直接打开openai至少还能访问成功,但是使用revchatgpt项目,那成功率非常低 ,我确定不是我代理配置错了

### ISSUE THREAD

**Issue by qssq1** [RockChinQ/revLibs#59]
这个错误ssl错误头疼死我了,我直接跑revChatgpt成功率 换了好多个vpn,成功率极低 ,一般情况都是requests.exceptions.SSLError: HTTPSConnectionPool(host='bypass.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFE
rror(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by RockChinQ** [comment]
提供系统信息、代理软件是否正常工作、revcfg填写的代理地址是否正确

**Comment by RockChinQ** [comment]
代理有问题，怎么搭建的代理？

**Comment by RockChinQ** [comment]
我使用的是 hutao.cloud

**Comment by RockChinQ** [comment]
你在revcfg.py中设置了账户使用的代理地址了吗？如果没设置，尝试设置一下，如果设置了，尝试删除那个代理设置

**Comment by RockChinQ** [comment]
github访问不了是网络问题

**Comment by RockChinQ** [comment]
更新一下逆向插件`!plugin update`
