### ISSUE TITLE
使用的代理库会导致使用access_token的账号被封停，请注意！

### ISSUE THREAD

**Issue by ZYKJShadow** [RockChinQ/revLibs#63]

**Comment by RockChinQ** [comment]
请尽可能提供更加详细的说明以确定封禁是否与逆向库有关

**Comment by ZYKJShadow** [comment]
> 请尽可能提供更加详细的说明以确定封禁是否与逆向库有关

duti.tech ，tg群目前用这个代理库的无一幸免

**Comment by ZYKJShadow** [comment]
![image](https://user-images.githubusercontent.com/45745703/225215053-c61ce160-4baf-42b1-9782-01de1f15ab93.png)

**Comment by ZYKJShadow** [comment]
建议把这个网址替换成 https://chat.gateway.do 
这个是ja-netfilter开发者搭建的

**Comment by RockChinQ** [comment]
> 建议把这个网址替换成 https://chat.gateway.do 
> 这个是ja-netfilter开发者搭建的

可否改为使用官方的api地址？

**Comment by ZYKJShadow** [comment]
> > 建议把这个网址替换成 https://chat.gateway.do
> > 这个是ja-netfilter开发者搭建的
> 
> 可否改为使用官方的api地址？

不行的，会被cf拦下来

**Comment by ZYKJShadow** [comment]
希望能接入这个，比较稳定，没出事：https://github.com/pengzhile/pandora

**Comment by RubiscoQAQ** [comment]
> 建议把这个网址替换成 https://chat.gateway.do 这个是ja-netfilter开发者搭建的

请问这行代码具体在哪个文件中呢？

**Comment by ZYKJShadow** [comment]
> chat.gateway.do

https://github.com/pengzhile/pandora/blob/master/src/pandora/openai/api.py

**Comment by ZYKJShadow** [comment]
> > 建议把这个网址替换成 https://chat.gateway.do 这个是ja-netfilter开发者搭建的
> 
> 请问这行代码具体在哪个文件中呢？

https://github.com/pengzhile/pandora/blob/master/src/pandora/openai/api.py

**Comment by RubiscoQAQ** [comment]
> > > 建议把这个网址替换成 https://chat.gateway.do 这个是ja-netfilter开发者搭建的
> > 
> > 
> > 请问这行代码具体在哪个文件中呢？
> 
> https://github.com/pengzhile/pandora/blob/master/src/pandora/openai/api.py

谢谢，但我想问的是BASE_URL = environ.get()这行代码。如果要修改代理网址应该在哪里修改呢？

**Comment by ZYKJShadow** [comment]
你引用的逆向库的代码在这里：https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/V1.py

但我并不确定直接更换这个url是否能解决这个问题，刚才咨询了ja-netfilter，没有得到肯定的回复

**Comment by ZYKJShadow** [comment]
目前来看，acheong08/ChatGPT这个库很多人在使用，大概率已经引起了OpenAI官方的注意，凡是他所开源的代码都有一定风险，不建议再使用

**Comment by RockChinQ** [comment]
根据`acheong08/ChatGPT`的文档，现已没有此问题
