### ISSUE TITLE
问任何问题都报错: KeyError: 'message'

### ISSUE THREAD

**Issue by yuxiaoyu8192** [RockChinQ/revLibs#7]
```
[CHAT]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "/bot/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 83, in process_message
    raise e
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 47, in process_message
    for section in session.get_reply(prompt):
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 44, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 54, in get_reply
    yield reply['message'], reply
KeyError: 'message'
```
![image](https://user-images.githubusercontent.com/103018181/219864638-878b72bc-6b28-4fd2-954e-f920ef8c1a83.png)

**Comment by RockChinQ** [comment]
1. 尝试将revcfg.py中的重试次数调高（8次左右）
2. 尝试使用accessToken的登录方式，见 #4 
3. 尝试更新，见 #1

**Comment by yuxiaoyu8192** [comment]
使用accessToken的登录方式之后就好了，谢谢解答！！！

**Comment by yuxiaoyu8192** [comment]
补充一点：单个账号多次提问后，好像会“Too many requests in 1 hour. Try again later.”s所以会有这个报错
![image](https://user-images.githubusercontent.com/103018181/219869100-84f9e0b2-1ee0-40a0-aa3d-6caa22992a64.png)

**Comment by RockChinQ** [comment]
> 补充一点：单个账号多次提问后，好像会“Too many requests in 1 hour. Try again later.”s所以会有这个报错 ![image](https://user-images.githubusercontent.com/103018181/219869100-84f9e0b2-1ee0-40a0-aa3d-6caa22992a64.png)

对的，接下来会做多账户支持

**Comment by RockChinQ** [comment]
> > 使用accessToken的登录方式之后就好了，谢谢解答！！！
> 
> 大佬您好，我用config里面的网站获取accessToken，提示openAI拒绝访问，但我用机场能进OPENAI的官网和邮箱，请问大佬是怎么获取到token的。还有就是access token就是 api-key吗？ （就那个sk-开头的？）

可以尝试换个节点重试一下，记得挂全局代理，然后使用隐私模式；access_token与apikey不是一个东西

**Comment by KevinYamazaki** [comment]
> > > 使用accessToken的登录方式之后就好了，谢谢解答！！！
> > 
> > 
> > 大佬您好，我用config里面的网站获取accessToken，提示openAI拒绝访问，但我用机场能进OPENAI的官网和邮箱，请问大佬是怎么获取到token的。还有就是access token就是 api-key吗？ （就那个sk-开头的？）
> 
> 可以尝试换个节点重试一下，记得挂全局代理，然后使用隐私模式；access_token与apikey不是一个东西

已解决，感谢作者！
