### ISSUE TITLE
希望适配内容转音频服务

### ISSUE THREAD

**Issue by niliovo** [RockChinQ/revLibs#77]
https://github.com/oliverkirk-sudo/chat_voice 此插件与EdgeGPT冲突，希望能够适配，让New bing的回复转语音

**Comment by RockChinQ** [comment]
现在逆向库插件会在获取到回复后触发`NormalMessageResponded`事件，故理论上其他插件能通过此事件被触发，see: https://github.com/RockChinQ/revLibs/pull/219
