### ISSUE TITLE
在接口拒绝对话时自动重置对话

### ISSUE THREAD

**Issue by IamChocolate** [RockChinQ/revLibs#89]
请您认真填写以下信息。

### 任务

- [*] 我已严格按照文档中的步骤操作
- [*] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：New Bing

### 期望情况

我希望的情况是：在接口拒绝对话时自动重置对话

### 实际情况

实际情况是：手动!reset重置 并且由于默认账号重用时间过长导致一段时间后就需要手动重置 几乎处于不可使用的状态

**Comment by RockChinQ** [comment]
请更新
