### ISSUE TITLE
安装老是提示这个，安完每次运行前也会有这个提示，怎么看回答切换成功了？

### ISSUE THREAD

**Issue by Reim** [RockChinQ/revLibs#9]
```WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /RockChinQ/QChatGPT/info/refs?service=git-upload-pack 
[2023-02-19 10:28:07.244] connectionpool.py (812) - [WARNING] : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /RockChinQ/QChatGPT/info/refs?service=git-upload-pack```

**Comment by Reim** [comment]
检查更新失败:HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /RockChinQ/QChatGPT/info/refs?service=git-upload-pack (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe4ce6ba6a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by Reim** [comment]
我现在第一次进可以，reload之后会报ModuleNotFoundError: No module named 'lxml'这个错。 我想知道怎么判断这个插件正常运作，返回得消息是用对的

**Comment by RockChinQ** [comment]
> reload之后会报ModuleNotFoundError: No module named 'lxml'这个错。 我想知道怎么判断这个插件正常运作，返回得消息是用对的 然后每次进会有个这个提示，安装了也提示 [2023-02-19 11:22:08.219] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn
> 
> pip 22.0.4 / python3.9.15

你是哪个插件遇到这个问题？请到插件仓库反馈

**Comment by RockChinQ** [comment]
原问题是主机无法正常访问github以检查主程序更新，这个一般不影响正常使用，若需要更新可以参考wiki常见问题页的更新方法
