### ISSUE TITLE
安装revLibs插件出现问题

### ISSUE THREAD

**Issue by wdnmdbw** [RockChinQ/revLibs#94]
请您认真填写以下信息。

### 任务

- [ ] 我已严格按照文档中的步骤操作
- [ ] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：New Bing

### 期望情况

我希望的情况是：正确安装revLibs

### 实际情况

实际情况是：QQ端输入!plugin https://gitee.com/RockChin/revLibs 后，控制台显示[2023-03-24 14:36:20.761] host.py (151) - [INFO] : 克隆插件储存库: https://gitee.com/RockChin/revLibs
Enumerating objects: 488, done.
Counting objects: 100% (488/488), done.
Compressing objects: 100% (275/275), done.
Total 488 (delta 259), reused 387 (delta 158), pack-reused 0
copied 487 pack entries87/488
[2023-03-24 14:36:21.682] host.py (156) - [INFO] : 检测到requirements.txt，正在安装依赖
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting revChatGPT~=4.0.6
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/69/d8/49ec067cbdd416397dc384723529886c3ec9133efb8dd5df1e79bc8d682f/revChatGPT-4.0.6.1-py3-none-any.whl (35 kB)
ERROR: Could not find a version that satisfies the requirement EdgeGPT~=0.1.6 (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.10, 0.0.11, 0.0.20, 0.0.21, 0.0.25, 0.0.30, 0.0.40, 0.0.41, 0.0.41.1, 0.0.42, 0.0.43, 0.0.44, 0.0.45, 0.0.46, 0.0.47, 0.0.48, 0.0.49, 0.0.50, 0.0.51, 0.0.53, 0.0.53.1, 0.0.54, 0.0.55, 0.0.56, 0.0.56.1, 0.0.56.2, 0.0.57, 0.0.58.1, 0.0.58.2, 0.0.59, 0.0.60, 0.1.0, 0.1.1, 0.1.2, 0.1.3)
ERROR: No matching distribution found for EdgeGPT~=0.1.6

**Comment by RockChinQ** [comment]
不要使用阿里源，更换有此版本的源
